URL_BASE = 'https://www.dane.gov.co'
DATA_URL = 'https://www.dane.gov.co/index.php/estadisticas-por-tema/agropecuario/sistema-de-informacion-de-precios-sipsa/mayoristas-boletin-semanal-1'
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

CATEGORIES_DICT  = {
            1: 'verduras_hortalizas',
            2: 'frutas_frescas',
            3: 'tuberculos_raices_platanos',
            4: 'granos_cereales',
            5: 'huevos_lacteos',
            6: 'carnes',
            7: 'pescados',
            8: 'productos_procesados'
        }
CITY_TO_REGION = {
        'barranquilla': 'caribe',
        'cartagena': 'caribe',
        'santa marta': 'caribe',
        'valledupar': 'caribe',
        'montería': 'caribe',
        'sincelejo': 'caribe',
        'riohacha': 'caribe',
        'ciénaga': 'caribe',
        'magangué': 'caribe',
        'maicao': 'caribe',
        'turbo': 'caribe',
        'lorica': 'caribe',
        'sahagún': 'caribe',
        'aracataca': 'caribe',
        'el banco': 'caribe',
        'girardot': 'andina',
        'ibagué': 'andina',
        'neiva': 'andina',
        'pereira': 'andina',
        'manizales': 'andina',
        'armenia': 'andina',
        'cali': 'pacífico',
        'buenaventura': 'pacífico',
        'tuluá': 'pacífico',
        'palmira': 'pacífico',
        'pasto': 'pacífico',
        'popayán': 'pacífico',
        'tumaco': 'pacífico',
        'yumbo': 'pacífico',
        'quibdó': 'pacífico',
        'bogotá': 'andina',
        'medellín': 'andina',
        'bucaramanga': 'andina',
        'cúcuta': 'andina',
        'villavicencio': 'orinoquía',
        'yopal': 'orinoquía',
        'arauca': 'orinoquía',
        'florencia': 'amazonía',
        'mocoa': 'amazonía',
        'leticia': 'amazonía',
        'puerto carreño': 'orinoquía',
        'mitú': 'amazonía',
        'inírida': 'amazonía',
        'bogota': 'andina',
        'duitama': 'andina',
        'ipiales': 'pacífico',
        'pamplona': 'andina',
        'sogamoso': 'andina',
        'tunja': 'andina',
        'cartago': 'pacífico',
        'rionegro': 'andina',
        'san gil': 'andina',
        'socorro': 'andina',
        'chiquinquirá': 'andina',
        'el santuario': 'andina',
        'marinilla': 'andina',
        'cajamarca': 'andina',
        'carmen de viboral': 'andina',
        'la ceja': 'andina',
        'san vicente': 'andina',
        'sonsón': 'andina',
        'peñol': 'andina',
        'santa bárbara': 'andina',
        'yarumal': 'andina',
        'la virginia': 'andina',
        'la unión': 'andina',
        'la parada': 'andina',
        'la dorada': 'andina',
        'charalá': 'andina',
        'güepsa': 'andina',
        'moniquirá': 'andina',
        'puente nacional': 'andina',
        'santana': 'andina',
        'vélez': 'andina',
        'caparrapí': 'andina',
        'nocaima': 'andina',
        'villeta': 'andina',
        'honda': 'andina',
        'ubaté': 'andina',
        'cartagena frigorífico candelaria': 'caribe',
        'san marcos': 'caribe',
        'alvarado': 'andina',
        'espinal': 'andina',
        'lérida': 'andina',
        'purificación': 'andina',
        'venadillo': 'andina',
        'cereté': 'caribe',
        'san gilpanela': 'andina',
        'yolombó': 'andina',
        'malambo': 'caribe',
        'el carmen de viboral': 'andina',
        'túquerres': 'pacífico',
        'san andrés de tumaco': 'pacífico',
        'ancuyá': 'andina',
        'consacá': 'andina',
        'sandoná': 'andina',
        'ancuya': 'andina',
        'tibasosa': 'andina',
        'san sebastián de mariquita': 'andina'}